#!/bin/bash

cd /

wget http://mirror.freepbx.org/modules/packages/freepbx/freepbx-15.0-latest.tgz

tar xvfz freepbx-*.tgz

cd freepbx

./start_asterisk start

./install -n

firewall-cmd --permanent --zone=public --add-port=80/tcp --add-port=80/udp
firewall-cmd --reload

systemctl restart httpd
